name: Validate Imports

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JS import targets
        shell: pwsh
        run: .\.github\scripts\validate-imports.ps1
